# Generated by Django 4.2.2 on 2023-07-08 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_1_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcontent',
            name='image',
            field=models.ImageField(default='default_image.png', upload_to='images/'),
        ),
    ]
