# Generated by Django 4.2.2 on 2023-07-18 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project_1_app', '0002_blogcontent_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcontent',
            name='author',
        ),
    ]
