# Generated by Django 4.2.2 on 2023-07-18 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Project_1_app', '0003_remove_blogcontent_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcontent',
            name='author',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
